### ISSUE TITLE
Get only balance different to 0

### ISSUE THREAD

**Issue by techguydev** [adman9000/laravel-cryptopia#2]
Hi, thanks for this nice wrapper to the cryptopia Api

Is there a way to get only the  balance that are different to '0' when  calling  

$balances = $cryptopia->getBalances();

That function returns all the balance and when showing it in the view takes time to process and show only the ones that are different to '0', like this: 

                              @foreach ($balances as $balance)
                                        @if($balance['Total']!= '0')
                                            <tr>
                                                <td>{{$balance['Symbol']}}</td>
                                                <td> {{$balance['Total']}}</td>
                                                <td> {{$balance['Available']}}</td>
                                            </tr>
                                        @endif
                                    @endforeach

Thanks

**Comment by adman9000** [comment]
Doesn't seem to be unfortunately. Only option appears to be getting all balances and then looping through to remove empty ones.
